version: '3.3'

services:
  backend:
    build:
      context: .
    depends_on:
      - db
  tasks:
    command: gw-tasks
    depends_on:
      - db
      - queue
  db:
    image: postgres:12
    volumes:
      - woolgatherer-db-data:/var/lib/postgresql/data
  queue:
    image: rabbitmq:3

volumes:
  woolgatherer-db-data:
