version: '3.3'

services:
  backend:
    ports:
      - 8081:8000
    image: woolgatherer:stage
    environment:
      - LOGLEVEL=debug
  tasks:
    image: woolgatherer:stage
    environment:
      - LOGLEVEL=debug
