version: '3.3'

services:
  backend:
    build:
      args:
        - PIP_CMD=pip install -e
    volumes:
      - .:/var/www/woolgatherer/
    environment:
      - DEBUG=1
      - LOGLEVEL=debug
  tasks:
    environment:
      LOGLEVEL: debug
    volumes:
      - .:/var/www/woolgatherer/
