version: '3.3'

services:
  backend:
    build:
      context: .
    depends_on:
      - db
    environment:
      GW_CACHE_URL: redis://cache
    restart: unless-stopped
    image: woolgatherer
  tasks:
    command: gw-tasks
    environment:
      SCHEDULE_FILE: /home/gw/celerybeat-schedule
    depends_on:
      - db
      - queue
    restart: unless-stopped
    image: woolgatherer
  db:
    image: postgres:12-alpine
    volumes:
      - woolgatherer-db-data:/var/lib/postgresql/data
    restart: unless-stopped
  queue:
    image: rabbitmq:3-alpine
    restart: unless-stopped
  cache:
    image: redis:5-alpine
    volumes:
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
  auth:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: keycloak
    depends_on:
      - db

volumes:
  woolgatherer-db-data:
