version: '3.3'

services:
  backend:
    build:
      args:
        - PIP_CMD=pip install -e
    ports:
      - 8082:8000
    image: woolgatherer:dev
    volumes:
      - .:/var/www/woolgatherer/
    environment:
      - DEBUG=1
      - LOGLEVEL=debug
  tasks:
    image: woolgatherer:dev
    environment:
      - LOGLEVEL=debug
    volumes:
      - .:/var/www/woolgatherer/
