#!/bin/sh

PORT="${PORT:-8000}"
HOST="${HOST:-0.0.0.0}"
WORKERS="${WORKERS:-1}"
LOGLEVEL="${LOGLEVEL:-info}"

if [ "$1" = "--dev" ]; then
  uvicorn woolgatherer:app --reload --host $HOST --port $PORT
else
  gunicorn -k uvicorn.workers.UvicornWorker -b "$HOST:$PORT" woolgatherer:app -w $WORKERS
fi
