#!/bin/sh

WORKERS="${WORKERS:-1}"
LOGLEVEL="${LOGLEVEL:-info}"
BIND="${HOST:-0.0.0.0}:${PORT:-8000}"

PARAMS=""
if [ -n "$RELOAD" ]; then
  PARAMS="$PARAMS --reload"
fi

gunicorn -k uvicorn.workers.UvicornWorker -b $BIND woolgatherer:app -w $WORKERS $PARAMS
