#!/usr/bin/env python
"""
A script which creates the db for the woolgatherer service
"""
from argparse import ArgumentParser, Namespace
from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database

from woolgatherer.db_models.base import DBBaseModel
from woolgatherer.utils.settings import Settings


def parse_args() -> Namespace:
    """ Parse the command line arguments """
    parser = ArgumentParser(
        "gw-createdb",
        description="""Script to create a database and associated tables if desired""",
    )
    parser.add_argument(
        "-t",
        "--create-tables",
        default=False,
        action="store_true",
        help="""Also create the tables in addition to the database.""",
    )

    return parser.parse_args()


def create_db(create_tables: bool = False) -> None:
    """ Create the database """
    if not database_exists(Settings.dsn):
        create_database(Settings.dsn)

    if create_tables:
        engine = create_engine(Settings.dsn)
        DBBaseModel.__metadata__.create_all(bind=engine)


def main():
    """ Main entry-point for the script """
    args = parse_args()

    create_db(create_tables=args.create_tables)


if __name__ == "__main__":
    main()
